site_name:  'UCLA OARC Sandbox'
# repo_url: https://github.com/IDREsandbox/sandbox
theme:
  name: material
  logo: logo.png
  # add alt text to the logo
  use_directory_urls: true
  scheme: slate
  palette:
    primary: "white"
    accent: "amber"

  font:
    text: "Roboto"
    code: "Roboto Mono"
  language: "en"
  features:
    # - navigation.footer
    - navigation.tabs
    - navigation.indexes
extra:
  generator: false
  logo_alt: "UCLA OARC Sandbox"


home_page: /learn/

# Navigation
nav:
  # - "tags": work/tags/index.md
  - Learn: learn/index.md
  - "Work": work/index.md
    # - "Workshops": learn/resources.md
    # - "Tutorials": learn/tutorials.md
  - "Muse": musings/index.md
  - Consult:
    - "Consult": consult/index.md
    - "Connect with us": consult/connect/index.md
    - "Where is the Sandbox?": consult/where/index.md

extra_css:
  # - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css
  - css/style.css
  # - https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism.css
  - css/prism.css

  
extra_javascript:
  - https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js
  - https://cdn.jsdelivr.net/npm/marked/marked.min.js
  # - https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/prism.min.js
  - js/prism.js
  - js/getdata.js
  - js/sheets_data.json


# Extensions
markdown_extensions:
  - markdown.extensions.codehilite
  - tables
  - attr_list
  - md_in_html
  # Python Markdown
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - meta

plugins:
  # - search
  - glightbox
  # - blog:
      # blog_dir: musings